### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by yd41** [Stardust1001/WebVPN#1]
![image](https://github.com/Stardust1001/WebVPN/assets/93515322/d074a652-7ec6-4a93-909b-67c8dd7403ff)
![image](https://github.com/Stardust1001/WebVPN/assets/93515322/70ce3ad6-4286-48af-af21-a879fe2f959c)
Hello AUthor:
When I deploy and run, accessing the URL encounters the above problem. How should I solve it？

**Comment by Stardust1001** [comment]
配置 dns 泛解析到你的域名，使用80端口运行程序，仅修改 site 网址为你的域名网址，就像下面截图1的配置这样。然后启动程序，你可以访问 http://www.hyzxvip.com，这就是 webvpn 的 home 网址，如截图2，你可以在第一个输入框里输入你要访问的网址，程序将自动在第二个输入框里转换出代理后的网址供你访问。整个 web 世界的所有域名，都是 webvpn 的二级域名，webvpn将为你带来一个全新的傀儡世界，其通过两千行的代码，做出了一个 js "沙盒"，在其傀儡域名下运行的目标域名网站，"几乎"无法发现自身处于 webvpn 的沙盒中。

Configure dns to pan-resolve to your domain name, use port 80 to run the program, and only modify the site URL to your domain name URL, just like the configuration in Screenshot 1 below. Then start the program, you can visit http://www.hyzxvip.com, which is the home URL of webvpn, as shown in screenshot 2, you can enter the URL you want to visit in the first input box, and the program will automatically The proxy URL will be converted into an input box for you to access. All domain names in the entire web world are the second-level domain names of webvpn. Webvpn will bring you a brand new puppet world. It uses two thousand lines of code to create a js "sandbox" under its puppet domain name. It is "almost" impossible for a website running on a target domain name to find itself in webvpn's sandbox.


![image](https://github.com/Stardust1001/WebVPN/assets/18097561/35297a62-dfa5-49c1-a3bd-2ebd92fe28f5)

&nbsp;


星尘
***@***.***

![image](https://github.com/Stardust1001/WebVPN/assets/18097561/62b15fc5-6f77-4437-8643-37c1af1556c6)


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月10日(星期五) 上午10:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Stardust1001/WebVPN] Invalid URL (Issue #1)














 
image.png (view on web)
 image.png (view on web)
 Hello AUthor:
 When I deploy and run, accessing the URL encounters the above problem. How should I solve it？

**Comment by yd41** [comment]
![Snipaste_2024-05-10_11-24-32](https://github.com/Stardust1001/WebVPN/assets/93515322/e5aae108-a869-4d1f-9b94-45085e1ea8cb)
![image](https://github.com/Stardust1001/WebVPN/assets/93515322/256b200b-2451-47a5-a425-be7bda1d23d5)
![image](https://github.com/Stardust1001/WebVPN/assets/93515322/18f391be-32f2-47fc-a813-433295cdec78)

我重新试了下，依旧是这个url错误，请问应该怎么解决呢

**Comment by Stardust1001** [comment]
配置 site: new URL('http://www.hyzxvip.com')
www 二级域名是通用的网站主域名，这个作为 webvpn 的首页

**Comment by Stardust1001** [comment]
另外，你的 dns 解析是泛解析吗？应该配置 \*.hyzxvip.com 指向你的服务器IP，重要的是 "\*"，这个表示整个 hyzxvip.com 的所有子域名皆被程序管理了，可以处理任意二级域名、多级域名

**Comment by yd41** [comment]
泛解析这边无法做到，请问必须要泛解析吗

**Comment by Stardust1001** [comment]
必须泛解析，因为所有域名都被转换成了 webvpn 的二级域名。这个域名属于你吧？那可以设置泛解析的。要么你可以本地电脑上试试 dnsmasq ，这个可以在本地电脑做 dns 解析

**Comment by yd41** [comment]
好的，我试试

**Comment by yd41** [comment]
![image](https://github.com/Stardust1001/WebVPN/assets/93515322/665c98ad-e77c-45f9-9140-09da4b131a62)
你好，请问有之前这种不需要泛解析的代码吗？这边出于一些原因不能泛解析

**Comment by Stardust1001** [comment]
IP部署的方式有问题，后续很多功能修复都是针对域名的方式，有不少问题已经不对IP部署的修复了。非常建议使用泛解析，如果只是自己用，可以本机电脑用 dnsmasq 来做泛解析。如果确实不能泛解析，可以看看分支 urlbased，可能存在一些问题。

**Comment by Stardust1001** [comment]
随便买一个域名，低至30块钱可以买到。另外 webvpn 要求占用80端口，所以一个服务器只能部署一个 webvpn 程序，80端口不能给其他程序用了，服务器可以租用一个星期的，不到50块钱。即使是泛解析的方式，webvpn也可能存在少许的问题，如果发现了，可以找出问题通知我修复或自行研究

**Comment by Stardust1001** [comment]
目前经过大量尝试，诸如公司、学校官网，都运行正常，大多数其他网站也都几无问题，代理百度、谷歌的使用体验都还不错，极少数情况下存在一点细微的问题，如腾讯、优酷等网站的视频无法播放（这也是视频网站最重要保护的东西，所以代理这些视频难度巨大，但仍然解决了很多）

**Comment by Lijuming33** [comment]
> 随便买一个域名，低至30块钱可以买到。另外 webvpn 要求占用80端口，所以一个服务器只能部署一个 webvpn 程序，80端口不能给其他程序用了，服务器可以租用一个星期的，不到50块钱。即使是泛解析的方式，webvpn也可能存在少许的问题，如果发现了，可以找出问题通知我修复或自行研究

80端口其他程序要用，我的做法是设置node的端口为9980，另外使用nginx代理9980即可完美复现该项目。
server {
    listen       80;
    listen       443 ssl;
    server_name  webvpn.com *.webvpn.com;

	
	if ($scheme = http) {
		rewrite ^(.*)$ https://$host$1 permanent;
	}

	ssl_certificate		ssl/cert.cer;
	ssl_certificate_key ssl/cert.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    proxy_set_header Host $host;
    proxy_set_header Webvpn-Scheme $scheme;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location / {
        proxy_pass http://127.0.0.1:9980;
    }
}

**Comment by Stardust1001** [comment]
可以的，不过还是要泛解析占用整个域名。另外，之前我试过用 nginx，但是 nginx 在中间会部分修改请求头、响应头，这些不应该动，所有请求头、响应头都该由 webvpn 来处理，所以我用 webvpn 自行占用 80 端口不用 nginx 做任何代理，此外 nginx 在中间代理或多或少会带来一些传输速度的影响

**Comment by yd41** [comment]
好的，谢谢

**Comment by Stardust1001** [comment]
done

**Comment by assassinliujie** [comment]
> 可以的，不过还是要泛解析占用整个域名。另外，之前我试过用 nginx，但是 nginx 在中间会部分修改请求头、响应头，这些不应该动，所有请求头、响应头都该由 webvpn 来处理，所以我用 webvpn 自行占用 80 端口不用 nginx 做任何代理，此外 nginx 在中间代理或多或少会带来一些传输速度的影响

想询问一下，如果不使用nginx这些来配置ssl证书的话，该如何配置呢，如果想用NGINX配证书的话，main.js里还要开启https吗。
比如能否main.js里写
  httpsEnabled: false,
  // WebVPN 服务端口
  port: 880,
  // WebVPN https 服务端口
  httpsPort: 8443,
  // WebVPN 服务网址，访问其他网站，都从这个网址进行转换
  site: new URL('http://www.webvpn.info'),
然后nginx里配置
server_name webvpn.com *.webvpn.com;
proxy_pass localhost:880;
呢。
或者如果把项目部署到docker里后，外界访问时，这个又该如何配置呢。因为手头的服务器80/443端口都已经被nginx占用了，没法腾出来

**Comment by MoonCakeMC** [comment]
您好

我这边将泛解析设置为 `*.webvpn.example.com`  
配置文件中填写
`site: new URL('http://home.webvpn.example.com'),`
访问 `http://home.webvpn.example.com` 还是会报 `Invalid URL`

请问是不支持泛解析的二级域名吗

**Comment by Stardust1001** [comment]
你要有自己的域名，解析到运行程序所在的服务器IP，site: new URL('https://www.yourdomain.com')，然后 https://www.yourdomain.com&nbsp;就是 webvpn 的服务网址，接着可以代理全世界所有网站




星辰
***@***.***

**Comment by MoonCakeMC** [comment]
我有自己的域名，使用`example.com`是因为我刻意隐去了我的真实域名

因为主域名下存在其他解析，所以希望使用`www.webvpn.example.com`作为 webvpn 的服务网址  
webvpn 代理后使用形如`www__example2__com.webvpn.example.com`的域名代理访问`www.example2.com`

请问现在是否支持这样操作，感谢您的答复

**Comment by Stardust1001** [comment]
我示例写的是 https://www.webvpn.info，那你有域名也该是这个样子，www.example.com，而不是&nbsp; www.webvpn.example.com。site 就是 https://www.example.com。然后可以代理所有网站。如果你想特定某个二级域名代理某个目标域名，可以在 config.js 里的 subdomains 配置，示例是有的




星辰
***@***.***
